name: metsim
channels:
  - conda-forge
dependencies:
  - python>=3.5
  - xarray>=0.11.0
  - pandas
  - netcdf4>=1.2.5
  - numba
  - numpy>=1.11.2
  - scipy>=0.18.1
  - dask
  - distributed
  - toolz
  - pytest
